[package]
name = "server"
version = "0.1.0"
authors = ["Microsoft Corp"]
edition = "2018"

[dependencies]
com = { path = "../../.." }
interface = { path = "../interface" }

[lib]
crate-type = ["rlib", "cdylib"]